plugins {
    id "com.android.application"
}

android {
    namespace "my.boxman"
    compileSdk 34
    useLibrary "org.apache.http.legacy"

    defaultConfig {
        applicationId "my.boxman"
        minSdk 23
        targetSdk 28
        versionCode 20
        versionName "9.89-festival-box-hint"
    }
}

dependencies {
    implementation fileTree(include: ["*.jar"], dir: "libs")
    implementation project(":festival-solver")
}
